python:
  - 3.15
python_impl:
  - cpython
numpy:
  - 2.5
gil_type:
  - normal
  # Will be enabled as part of https://anaconda.atlassian.net/browse/PKG-5855
  - disabled

# TODO: Windows tail-calling interpreter: 64-bit builds with Visual Studio 2026 (MSVC 18) can now use the tail-call interpreter (reported ~15–20% speedup).
# Official python.org Windows binaries now use it.
# We should consider adding vs2026 and use it for later builds.
# c_compiler:                   # [win]
#   - vs2026                    # [win]
# c_stdlib_version:             # [win]
#   - 2026.1                    # [win]
# cxx_compiler:                 # [win]
#   - vs2026                    # [win]
