python:
  - 3.10
python_impl:
  - cpython
libffi:  # [win]
  - 3.4  # [win]
numpy:
  - 1.16
readline_mode:
  - readline
  - editline
  - none
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
