python:
  - 3.8
  - 3.8
  - 3.8
c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
vc:                            # [win]
  - 14.1                       # [win]
MACOSX_SDK_VERSION:            # [osx and arm64]
  - 11.1                       # [osx and arm64]
