python:
  - 3.9
python_impl:
  - cpython
numpy:
  - 1.16
vc:                            # [win]
  - 14                         # [win]
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - 11.0                       # [osx and x86_64]
