{% set version = "3.5.4" %}
{% set md5 = "2ed4802b7a2a7e40d2e797272bf388ec" %}

package:
  name: python
  version: {{ version }}

source:
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  md5: {{ md5 }}
  patches:
    - 0001-Issue-21122-Fix-LTO-builds-on-OS-X.-Patch-by-Brett-C.patch
    - 0002-Add-Anaconda-Distribution-version-logic.patch
    - 0003-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
    - 0004-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
    - 0005-Win32-distutils-Also-look-for-executable.bat.patch
    - 0006-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
    - 0007-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
    - 0008-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
    - 0009-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    - 0010-Support-cross-compiling-byte-code.patch
    - 0011-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
    - 0012-Fallback-to-system-compilers-if-psuedo-cross-compile.patch
    - 0013-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch

build:
  number: 3
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.5     # [unix]
  track_features:
    - vc14              # [win]
  script_env:
    - python_branding

requirements:
  host:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 7.*      # [unix]
    - sqlite 3.16.*     # [unix]
    - tk 8.6.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 6.0.*     # [linux]
    - libffi 3.2.*      # [unix]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - pkg-config        # [unix]
  run:
    - openssl 1.0.*     # [unix]
    - readline 7.*      # [unix]
    - sqlite 3.16.*     # [unix]
    - tk 8.6.*          # [unix]
    - xz 5.2.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 6.0.*     # [linux]
    - libffi 3.2.*      # [unix]
    - vs2015_runtime    # [win]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]
    - conda inspect linkages -p $PREFIX python  # [not win]
    - conda inspect objects -p $PREFIX python  # [osx]

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - pelson
    - ocefpaf
