{% set version = "2.7.13" %}
{% set sha256 = "a4f05a0720ce0fd92626f0278b6b433eee9a6173ddf2bced7957dfb599a5ece1" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-Anaconda-Distribution-version-logic.patch
    - 0002-Darwin-Hack-sys.-exec_-prefix-if-run-from-python.app.patch
    - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
    - 0004-Win32-distutils-Also-look-for-executable.bat.patch
    - 0005-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
    - 0006-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
    - 0007-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
    - 0008-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    - 0009-Fallback-to-system-compilers-if-psuedo-cross-compile.patch

build:
  number: 3
  no_link:
    - bin/python2.7     # [unix]
    - DLLs/_ctypes.pyd  # [win]
  track_features:
    - vc9               # [win]
  script_env:
    - python_branding

requirements:
  host:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 7.*      # [unix]
    - sqlite 3.16.*     # [unix]
    - tk 8.6.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 6.0.*     # [linux]
    - libffi 3.2.*      # [unix]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}
    - {{ cdt('libx11-devel') }}
    - pkg-config        # [unix]
  run:
    - openssl 1.0.*     # [unix]
    - readline 7.*      # [unix]
    - sqlite 3.16.*     # [unix]
    - tk 8.6.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 6.0.*     # [linux]
    - libffi 3.2.*      # [unix]
    - vs2008_runtime    # [win]

test:
  commands:
    - python -V
    - pydoc -h
    - python-config --help  # [unix]
    - idle -h

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - pelson
