{% set version = "3.6.2" %}
{% set md5 = "e1a36bfffdd1d3a780b1825daf16e56c" %}

package:
  name: python
  version: {{ version }}

source:
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  md5: {{ md5 }}
  patches:
    - 0001-Add-Anaconda-Distribution-version-logic.patch
    - 0002-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
    - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
    - 0004-Win32-distutils-Also-look-for-executable.bat.patch
    - 0005-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
    - 0006-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
    - 0007-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
    - 0008-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    - 0009-Support-cross-compiling-byte-code.patch
    - 0010-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
    - 0011-Fallback-to-system-compilers-if-psuedo-cross-compile.patch
    - 0012-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
    - 0013-Win32-Do-not-download-externals.patch

build:
  number: 10
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.6     # [unix]
  track_features:
    - vc14              # [win]
  script_env:
    - python_branding
  # We delete the shared libraries.
  ignore_run_exports:   # [unix]
    - bzip2             # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - pkg-config                         # [unix]
    - 7za                                # [win]
    - curl                               # [win]
  host:
    - bzip2                              # [unix]
    - sqlite                             # [unix]
    - xz                                 # [unix]
    - zlib                               # [unix]
    - openssl 1.0.*                      # [unix]
    - readline 7.*                       # [unix]
    - tk 8.6.*                           # [unix]
    - ncurses 6.0.*                      # [linux]
    - libffi 3.2.*                       # [unix]
  run:
    - openssl 1.0.*                      # [unix]
    - readline 7.*                       # [unix]
    - tk 8.6.*                           # [unix]
    - ncurses 6.0.*                      # [linux]
    - libffi 3.2.*                       # [unix]
    - vs2015_runtime                     # [win]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]
    - conda inspect linkages -p $PREFIX python  # [not win]
    - conda inspect objects -p $PREFIX python  # [osx]

about:
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: https://www.python.org/doc/versions/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://docs.python.org/devguide/

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - pelson
    - ocefpaf
