{% set version = "2.7.13" %}
{% set sha256 = "a4f05a0720ce0fd92626f0278b6b433eee9a6173ddf2bced7957dfb599a5ece1" %}

package:
  name: python
  version: {{ version }}

source:
  fn: Python-{{ version }}.tgz
  url: https://www.python.org/ftp/python/{{ version }}/Python-{{ version }}.tgz
  sha256: {{ sha256 }}
  patches:
      - osx-dist.patch                  # [osx and x86_64]
      - win-find_exe.patch              # [win]
      - win-library_bin.patch           # [win]

build:
  number: 0
  no_link:
    - bin/python2.7     # [unix]
    - DLLs/_ctypes.pyd  # [win]
  track_features:
    - vc9               # [win]
  script_env:
    - python_branding

requirements:
  build:
    - bzip2 1.0.*       # [unix]
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.13.*     # [unix]
    - tk 8.5.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]
  run:
    - openssl 1.0.*     # [unix]
    - readline 6.2*     # [unix]
    - sqlite 3.13.*     # [unix]
    - tk 8.5.*          # [unix]
    - zlib 1.2.*        # [unix]
    - ncurses 5.9*      # [linux]
    - vs2008_runtime    # [win]

test:
  commands:
    - python -V
    - pydoc -h
    - python-config --help  # [unix]
    - idle -h

about:
  home: http://www.python.org/
  license: PSF
  summary: General purpose programming language
      
extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - pelson
